[dependencies]

[package]
description = "a simple library for operator"
edition = "2021"
keywords = ["ternary", "no_std", "operator", "catch"]
license = "Unlicense"
repository = "https://github.com/cradiy/op.git"
name = "op"
readme = "README.md"
version = "0.1.4"